-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 20:01:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teste-vaga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste-vaga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste-vaga` DEFAULT CHARACTER SET utf8 ;
USE `teste-vaga` ;

-- -----------------------------------------------------
-- Table `teste-vaga`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste-vaga`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste-vaga`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste-vaga`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NOT NULL,
  `unidade_medida` VARCHAR(10) NOT NULL,
  `preco` FLOAT(6,2) NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `idprodutos_UNIQUE` (`id_produto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste-vaga`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste-vaga`.`forma_pagamento` (
  `id_forma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `desc_forma_pagamento` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_forma_pagamento`),
  UNIQUE INDEX `idformas_pagamento_UNIQUE` (`id_forma_pagamento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste-vaga`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste-vaga`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_forma_pagamento` INT NOT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `idpedido_UNIQUE` (`id_pedido` ASC),
  INDEX `fk_forma_pagamento_idx` (`id_forma_pagamento` ASC),
  INDEX `fk_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `teste-vaga`.`cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_forma_pagamento`
    FOREIGN KEY (`id_forma_pagamento`)
    REFERENCES `teste-vaga`.`forma_pagamento` (`id_forma_pagamento`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste-vaga`.`pedido_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste-vaga`.`pedido_item` (
  `id_pedido_item` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` FLOAT(4,2) NOT NULL,
  PRIMARY KEY (`id_pedido_item`),
  UNIQUE INDEX `idpedido_item_UNIQUE` (`id_pedido_item` ASC),
  INDEX `fk_pedido_idx` (`id_pedido` ASC),
  INDEX `fk_produto_idx` (`id_produto` ASC),
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `teste-vaga`.`pedido` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `teste-vaga`.`produto` (`id_produto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
